Created the Alert Preferences Figma Mock up
trevorwinser/Infinite-Loopers pull request #106
Opened 2024-03-07 21:40 UTC by noahstaz

Created the alert preferences figma mockup according to #90

2024-03-08 00:33 UTC, danglakshay requested changes
Design looks good, but maybe consider adding some information on how the alert system works? 

For example, as someone looking at the screen for the first time, I'm not sure what "Zone" means.

Adding a sidebar with information or just a couple of lines below each entry field would make the design much better for the user.

2024-03-09 00:07 UTC, trevorwinser commented
I agree with Lakshay. I think a simple information button that pops up with some text would be good. Like this: ⓘ

2024-03-09 21:47 UTC, noahstaz commented
@trevorwinser @danglakshay Updated the design to address concerns and looking for pr approval

2024-03-10 00:07 UTC, trevorwinser approved these changes

2024-03-10 01:26 UTC, danglakshay approved these changes

2024-03-10 03:11 UTC, merged