Graph visualizations
trevorwinser/Infinite-Loopers pull request #135
Opened 2024-03-18 05:05 UTC by komalsingh0925

1. Follow [(https://github.com/trevorwinser/Infinite-Loopers/blob/admin-dashboard-backend/Instructions/flask.md)]

2. Go to [http://127.0.0.1:5000/data-visualization]

3. Go to [http://127.0.0.1:5000/data-visualization/94/8]

4. While Flask is running, open visualization_test.py. There should be a green check mark shown at the bottom of the code. Click that and the tests will automatically run.

P.S Don't worry if filter_visualization.html or data_visualization.html highlight red. They don't cause any issues with the functionality of the system.

<img width="478" alt="image" src="https://github.com/trevorwinser/Infinite-Loopers/assets/81064099/e5f44b86-c5a8-4c23-929d-84f58e054826">

#129

2024-03-18 16:52 UTC, noahstaz requested changes
Merge conflicts should be looked at, __pycache should be added to gitignore, and then the app.py ones would be a more specific change

2024-03-19 04:23 UTC, julieflament commented
personally struggling with tests, but once again i think that is just an issue with my computer. from what i can see they look good. visualizations are great!

2024-03-19 04:54 UTC, julieflament commented
resolved conflicts but make sure to check all the files before merging.

2024-03-19 05:54 UTC, noahstaz approved these changes
Approved to merge if you update gitignore everything else is good and tests worked properly

2024-03-19 05:54 UTC, noahstaz commented on code/test/hurriscan.db
This should not be here I think your gitignore is outdated, update to the one on main before merge

2024-03-19 16:50 UTC, merged