Functional Login and Registration Page
trevorwinser/Infinite-Loopers pull request #139
Opened 2024-03-19 11:00 UTC by danglakshay

# Testing Instructions:

1. Follow https://github.com/trevorwinser/Infinite-Loopers/blob/admin-dashboard-backend/Instructions/flask.md
2. Run main.py (present in the code directory)
3. Go to http://127.0.0.1:5000/login
4.  Go to http://127.0.0.1:5000/sign-up
5. Test file for running basic tests can be found in Infinite-Loopers/code/test/test_auth.py

# Reasoning and Description:

The login page and Requirements page are functional and add data to the users.db file in the 'login' directory. The code is tested by running main.py instead of running app.py because the current directory structure of the project does not work with the architecture for the authorization functionality, a discussion about which will be brought up during the next sprint meeting.

Testing is currently basic and will be improved upon in the next sprint as knowledge and grasp of pytest increases.

## Kanban issues completed:
#93 #94

2024-03-19 20:17 UTC, noahstaz requested changes
Comments on the files :)

2024-03-19 20:17 UTC, noahstaz commented on code/login/models.py
This should be adjusted to hurrscan.db Users table is in there

2024-03-19 20:17 UTC, noahstaz commented on code/test/test_auth.py
> +
Removed some of the spacing; isn't too necessary

2024-03-22 20:06 UTC, trevorwinser approved these changes

2024-03-22 20:06 UTC, merged