Predictions visualizations
trevorwinser/Infinite-Loopers pull request #155
Opened 2024-03-24 23:08 UTC by komalsingh0925

In order to run predictions_test.py follow these steps:

1. Run the steps given here: https://github.com/trevorwinser/Infinite-Loopers/blob/main/Instructions/flask.md
2. FIx line 10 to make it to your path of the ChromeDriver Instance (or maybe just remove it i'm not sure about Mac)
3. If you want to test the functionality of the overall graph setup go on http://127.0.0.1:5000/temperature-predictions
4. Note if the graph doesn't load for some months it means that there is not any or enough data for those months

2024-03-25 01:11 UTC, julieflament requested changes
minor changes

2024-03-25 01:11 UTC, julieflament commented on code/app.py
> +    conn = sqlite3.connect('hurriscan.db')
add try/catch

2024-03-25 01:11 UTC, julieflament commented on code/app.py
> +    df = pd.read_sql_query("SELECT month, AVG(temp) AS avg_temp, AVG(humidity) AS avg_humidity, AVG(air) AS avg_air FROM Data GROUP BY month", conn)
make a function that returns humidity, temperature, and air based on month

2024-03-25 21:42 UTC, komalsingh0925 commented on code/app.py
> +    conn = sqlite3.connect('hurriscan.db')
This is done now

2024-03-25 23:09 UTC, trevorwinser commented on code/app.py
Traceback (most recent call last):
  File "C:\Users\trevo\OneDrive\Documents\Computer Science\COSC310\Infinite-Loopers\code\venv\Lib\site-packages\flask\cli.py", line 247, in locate_app
    __import__(module_name)
  File "C:\Users\trevo\OneDrive\Documents\Computer Science\COSC310\Infinite-Loopers\code\app.py", line 7, in <module>
    import pandas as pd
  File "C:\Users\trevo\OneDrive\Documents\Computer Science\COSC310\Infinite-Loopers\code\venv\Lib\site-packages\pandas\__init__.py", line 32, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
        
numpy import error. I will try to debug to see what's wrong.

2024-03-26 02:22 UTC, julieflament approved these changes
made necessary changes and tests run! good job!

2024-03-26 02:58 UTC, trevorwinser commented on code/app.py
Fixed by uninstalling numpy and pandas

2024-03-26 02:59 UTC, trevorwinser approved these changes
Looks good!

2024-03-26 03:00 UTC, merged