fixed formatting of user-dashboard
trevorwinser/Infinite-Loopers pull request #173
Opened 2024-03-31 07:03 UTC by julieflament

- fixed user-dashboard html and css
- left enough space for the nav bar
- we do not need the map-filter html anymore (ensure that we can delete both the HTML and CSS file)
- made front-end tests but need to check validity (was not able to check if they ran on my vscode)

- load http://127.0.0.1:5000/user_dashboard
- play around with the filters, the map, and the graphs

- test file is user_dashboard_test.py

2024-03-31 09:40 UTC, trevorwinser approved these changes

2024-03-31 23:37 UTC, komalsingh0925 requested changes

2024-03-31 23:37 UTC, komalsingh0925 commented on server/static/css/user-dashboard.css
> +    height: 550px;
Better practice would be to use % ages or 'ems' for css values so that its dynamic and works with different display sizes

2024-03-31 23:37 UTC, komalsingh0925 commented on server/static/css/user-dashboard.css
> +    border-radius: 10px;
same for the iframes here

2024-03-31 23:43 UTC, komalsingh0925 commented
map does not load up for me when testing by applying dates

2024-04-01 03:10 UTC, komalsingh0925 commented
> map does not load up for me when testing by applying dates

Latest commit made the map filter work accurately :)

2024-04-02 06:56 UTC, noahstaz commented on server/templates/user-dashboard.html
> +        // "useLocalExtrema": true,
Delete the comments

2024-04-02 10:16 UTC, danglakshay requested changes
The merge conflicts should be looked at before merging, but the formatting work itself looks good!

2024-04-02 19:31 UTC, julieflament commented
> The merge conflicts should be looked at before merging, but the formatting work itself looks good!

fixed!

2024-04-02 19:31 UTC, julieflament commented
> There are some code conflicts and some other issues

fixed merged conflicts!

2024-04-02 20:48 UTC, komalsingh0925 approved these changes

2024-04-02 20:56 UTC, merged